spring:  
  cloud: 
     bus: 
       trace: 
         enabled: true      
#---
#spring:
#  storeType:
#    file:
#      maxSize: 10737418240
#      fileMaxSize: 5242880
#      sizeThreshold: 4096
#      repository: C:\\dml\\uploadFileTemp\\
#      headerEncoding: utf-8 
---
spring:
  http: 
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb  
      
---
security:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  session:
     expireTime: 1800000
     


spring:
  session:
    store-type: redis    


                