spring:
  datasource:
      url: jdbc:mysql://192.168.174.128:3306/zipkin?createDatabaseIfNotExist=true&useUnicode\=true&characterEncoding\=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      schema: classpath:/zipkin.sql
      initialize: true
      continue-on-error: true
  redis:
      host: 192.168.174.128
      port: 6379    
  rabbitmq:
    host: 192.168.174.128
    port: 5673
    username: guest
    password: guest 
    timeout: 300 
    publisher-confirms: true
    virtual-host: /
   
---
      
spring:
  sleuth:
    enabled: false

#zipkin:
#  storage:
#    type: mysql

zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
#     cluster: elasticsearch
      hosts: 192.168.174.128:9300
      max-requests: 64
      index: zipkin
      index-shards: 5
      index-replicas: 1
        
---

spring:
  session:
    store-type: redis  
    
---
spring:
    data:
        elasticsearch:
          properties: 
            host: 192.168.174.128
            port: 9300
##            cluster-name: elasticsearch
#            cluster-nodes: 192.168.174.128:9300          