
spring:
  aop:
    proxy-target-class: true
    
eureka:
  instance:
        statusPageUrlPath: ${management.contextPath}/info
        healthCheckUrlPath: ${management.contextPath}/health
#        preferIpAddress: true
#        metadataMap:
#          instanceId: ${spring.application.name}:${random.value}
#        ip-address: localhost
#        secure-port: 1111
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
      healthcheck:
         enabled: true    
    registryFetchIntervalSeconds: 10

#---
#spring:
#  zipkin:
#    base-url: http://localhost:11020
---

#spring: 
#  zipkin:
#    base-url: http://localhost:9411
    
---

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
                      #这里将线程策略设置为SEMAPHORE
#           strategy: SEMAPHORE       
#        semaphore:
#          maxConcurrentRequests: 200

---          
feign:
  hystrix:
    enabled: true  
  httpclient:
    enabled: true
#            
#---
#hystrix:  
#  threadpool:  
#    default:  
#      coreSize: 500 #缺省为10       