# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
#fdfs:
#  soTimeout: 1501
#  connectTimeout: 601 
#  thumbImage:
#    width: 150
#    height: 150
#  trackerList:


---

fdfs:
  soTimeout: 1501
  connectTimeout: 601 
  thumbImage:
    width: 150
    height: 150
  trackerList:
     - 192.168.174.128:22122
  webServerUrl: http://192.168.174.128:8888/
#  pool:
#    #从池中借出的对象的最大数目
#    maxTotal: 153
#    #获取连接时的最大等待毫秒数100
#    maxWaitMillis: 102